### ISSUE TITLE
关于技能清单

### ISSUE THREAD

**Issue by mingyEx** [fawdlstty/fawdlstty#1]
关于[这个](https://github.com/fawdlstty#%E6%8A%80%E8%83%BD%E6%B8%85%E5%8D%95),是否有大部分人认为的标准线，达到者可以被认为是”拥有此技能“。
换句话说，我要做到哪些事才可以把自以为会的东西加上去而不会被人吐槽呢 =_=

**Comment by fawdlstty** [comment]
没有标准，想写就写
