### ISSUE TITLE
邀请收录进： awesome-github-profile-readme-chinese

### ISSUE THREAD

**Issue by eryajf** [fawdlstty/fawdlstty#2]
你好，你的个人主页很赞，我做了一个中文区优秀个人主页合集的项目，特邀请你参与贡献。

项目地址：https://github.com/eryajf/awesome-github-profile-readme-chinese

**Comment by fawdlstty** [comment]
感谢您的认可。您可加入收录

**Comment by eryajf** [comment]
方便的话，可以走个PR参与，这样你也会出现在贡献者列表当中

**Comment by fawdlstty** [comment]
我这边不便于截图，不pr了
